blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path("", views.blog_list,name="blog_list"),
    path("category/<cat>", views.blog_list,name="category"),
    path("author/<author>", views.blog_list,name="author"),
    path("detail/<slug>", views.blog_detail,name="blog_detail"),
    path("manage/", views.blog_manage,name="blog_manage"),
]

index/urls.py
from django.urls import path
from index import views

app_name = "index"

urlpatterns = [
    path("", views.home,name="home"),
    path("about/", views.about, name="about"),
    path("contact_us/", views.contact_us, name="contact_us"),
]

news/urls.py
from django.urls import path
from news import views

app_name = "news"

urlpatterns = [
    path("", views.news_list,name="news_list"),
    path("detail/", views.news_detail,name="news_detail"),
]

school_site/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("index.urls")),
    path("blog/", include("blog.urls")),
    path("news/", include("news.urls")),
    path("student/", include("student.urls")),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from student import views

app_name = "student"

urlpatterns = [
    path("", views.dashboard,name="dashboard"),
]

blog/models.py
from django.db import models
from django_jalali.db import models as jmodels
from django.contrib.auth.models import User

# Create your models here.

class BlogCategory(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


STATUS = (
    (0,"Draft"),
    (1,"Publish"),
    (2,"Archived"),
)

class BlogPost(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    lead = models.CharField(max_length=600)
    category = models.ManyToManyField(BlogCategory)
    author = models.ForeignKey(User, on_delete= models.SET_NULL,related_name='blog_posts',null=True)
    content = models.TextField()
    image = models.ImageField(upload_to="blog_images/",default="blog_images/default.png")
    updated_on = models.DateTimeField(auto_now= True)
    created_on = jmodels.jDateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    view_count = models.IntegerField(default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title


class BlogComment(models.Model):
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='comments')
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField()
    text = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-created_on']

student/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render
from blog.models import *
# Create your views here.

def blog_list(request,author="None",cat="None"):
    if author != "None":
        posts = BlogPost.objects.filter(status=1,author__username=author)
        #context = {'posts': posts, 'author': author}
    elif cat != "None":
        posts = BlogPost.objects.filter(status=1,category__name=cat)
       # context = {'posts': posts, 'cat': cat}
    else:
        posts = BlogPost.objects.filter(status=1)
        #context = {'posts': posts, }

    if request.method == 'GET' and request.GET.get('s'):
        s = request.GET.get('s')
        posts = posts.filter(title__contains=s)

    posts = Paginator(posts, 3)
    page_number = request.GET.get("page")

    try:
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)#کار نمیکنه
    except EmptyPage:
        posts = posts.get_page(1)#کار نمیکنه


    context = {'posts': posts, 'cat': cat, 'author': author}


    return render(request, "blog/blog_list.html", context)

def blog_detail(request,slug):
    post = BlogPost.objects.get(slug=slug)
    context = {'post': post}
    return render(request, "blog/blog_detail.html", context)

def blog_manage(request):
    posts = BlogPost.objects.all()
    context = {'posts': posts}
    return render(request, "blog/manage/admin-course-list.html",context)/

index/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,"index/school-home.html")

def about(request):
    return render(request,"index/about.html")

def contact_us(request):
    return render(request,"index/contact-us.html")

news/views.py
from django.shortcuts import render

# Create your views here.

def news_list(request):
    return render(request, "news/news_list.html")

def news_detail(request):
    return render(request, "news/news_detail.html")

student/views.py
from django.shortcuts import render

# Create your views here.

def dashboard(request):
    return render(request, "student/dashboard.html")

blog/templates/blog/blog_detail.html
{% extends "index/base.html" %}

{% load static %}

{% block content %}

{% load humanize %}

{% load jformat %}

{% load blog_tag %}

<!-- **************** MAIN CONTENT START **************** -->
<main>
	
<!-- =======================
Main Content START -->
<section class="pb-0 pt-4 pb-md-5">
	<div class="container">
		<div class="row">
			<div class="col-12">

				<!-- Title and Info START -->
				<div class="row">
					<!-- Avatar and Share -->
					<div class="col-lg-3 align-items-center mt-4 mt-lg-5 order-2 order-lg-1">
						<div class="text-lg-center">
							<!-- Author info -->
							<div class="position-relative">
								<!-- Avatar -->
								<div class="avatar avatar-xxl">
									<img class="avatar-img rounded-circle" src="{% static 'images/avatar/09.jpg' %}" alt="avatar">
								</div>
								<a href="{% url 'blog:author' author=post.author %}" class="h5 stretched-link mt-2 mb-0 d-block">{{ post.author.get_full_name }}</a>
								<p class="mb-2">{{ post.author.email }}</p>
							</div>
							<!-- Info -->
							<ul class="list-inline list-unstyled">
								<li class="list-inline-item d-lg-block my-lg-2">{{ post.author.date_joined|naturalday }}</li>
								<li class="list-inline-item d-lg-block my-lg-2">زمان مطالعه: 5 دقیقه</li>
								<li class="list-inline-item badge text-bg-orange"><i class="far text-white fa-heart me-1"></i>26</li>
								<li class="list-inline-item badge text-bg-info"><i class="far fa-eye me-1"></i>2K</li>
							</ul>
						</div>
					</div>

					<!-- Content -->
					<div class="col-lg-9 order-1">
						<!-- Pre title -->
						<span>{{ post.created_on|jformat:"%d %B %Y" }}</span><span class="mx-2">|</span><div class="badge text-bg-success">موضوع</div>
						<!-- Title -->
						<h1 class="mt-2 mb-0 display-5">{{ post.title }}</h1>
						<!-- Info -->
                        <p class="mt-2">{{ post.lead }}</p>
					</div>
				</div>
				<!-- Title and Info END -->

                <div class="row">
                    <div class="col-lg-7">
                        <img width="100%" class="img-thumbnail" src="{{ post.image.url }}" alt="{{ post.title }}">
                        	<div class="row mb-4">
						<h4 class="mt-4">تیتر یک</h4>
						<div class="col-md-12">
							<p class="mb-0">{{ post.content|snip:100 }}</p>
						</div>
					</div>
                    </div>
                    <div class="col-lg-5 d-none d-lg-block bg-body-tertiary">
                        {% popular_posts %}
                    </div>

                </div>
				<!-- Content START -->



				<!-- Content END -->

				<!-- Tags and share START -->
				<div class="d-lg-flex justify-content-lg-between mb-4">

					<!-- Social media button -->
					<div class="align-items-center mb-3 mb-lg-0">
						<h6 class="mb-2 me-4 d-inline-block">اشتراک گذاری در:</h6>
						<ul class="list-inline mb-0 mb-2 mb-sm-0">
							<li class="list-inline-item"> <a class="btn px-2 btn-sm bg-facebook" href="#"><i class="fab fa-fw fa-facebook-f"></i></a> </li>
							<li class="list-inline-item"> <a class="btn px-2 btn-sm bg-instagram-gradient" href="#"><i class="fab fa-fw fa-instagram"></i></a> </li>
							<li class="list-inline-item"> <a class="btn px-2 btn-sm bg-twitter" href="#"><i class="fab fa-fw fa-twitter"></i></a> </li>
							<li class="list-inline-item"> <a class="btn px-2 btn-sm bg-linkedin" href="#"><i class="fab fa-fw fa-linkedin-in"></i></a> </li>
						</ul>
					</div>

					<!-- Popular tags -->
					<div class="align-items-center">
						<h6 class="mb-2 me-4 d-inline-block">تگ ها:</h6>
						<ul class="list-inline mb-0 social-media-btn">
                            {% for tag in post.category.all %}
							    <li class="list-inline-item"> <a class="btn btn-outline-light btn-sm mb-lg-0" href="{% url 'blog:category' cat=tag.name %}">{{ tag.name }}</a> </li>
                            {% endfor %}
						</ul>
					</div>
				</div>
				<!-- Tags and share END -->

				<hr> <!-- Divider -->

				<!-- Comment review and form START -->
				<div class="row mt-4">
					<!-- Comment START -->
					<div class="col-md-7">
						<h3>3 کامنت</h3>
                        {% for comment in post.comments.all %}
						<!-- Comment level 1-->
						<div class="my-4 d-flex bg-body-tertiary p-3 rounded">
							<img class="avatar avatar-md rounded-circle me-3" src="{% static 'images/avatar/01.jpg' %}" alt="avatar">
							<div>
								<div class="mb-2">
									<h5 class="m-0">{{ comment.name }}</h5>
									<span class="me-3 small">{{ comment.created_on|jformat:"%d %B %Y" }}</span>
								</div>
								<p>{{ comment.text }}</p>
								<a href="#" class="btn btn-sm btn-light mb-0">پاسخ</a>
							</div>
						</div>
                        {% endfor %}

					</div>
					<!-- Comment END -->

					<!-- Form START -->
					<div class="col-md-5">
						<!-- Title -->
						<h3 class="mt-3 mt-sm-0">نظرات خود را با ما به اشتراک بگذارید</h3>
						<small>آدرس ایمیل شما منتشر نخواهد شد. فیلدهای ضروری با * مشخص شده‌اند.</small>

						<form class="row g-3 mt-2 mb-5">
							<!-- Name -->
							<div class="col-lg-6">
								<label class="form-label">نام *</label>
								<input type="text" class="form-control" aria-label="First name">
							</div>
							<!-- Email -->
							<div class="col-lg-6">
								<label class="form-label">ایمیل *</label>
								<input type="email" class="form-control">
							</div>
							<!-- Comment -->
							<div class="col-12">
								<label class="form-label">نظر شما *</label>
								<textarea class="form-control" rows="3"></textarea>
							</div>
							<!-- Button -->
							<div class="col-12">
								<button type="submit" class="btn btn-primary mb-0">Post comment</button>
							</div>
						</form>
					</div>
					<!-- Form END -->
				</div>
				<!-- Comment review and form END -->
            <hr> <!-- Divider -->
			</div>
		</div> <!-- Row END -->
	</div>
</section>
<!-- =======================
Main Content END -->



<!-- =======================
Related blog START -->
<section class="pt-0">
	<div class=" container">
        <div class="row">
            <div class="col-lg-6">
                {% last_posts 2 %}
            </div>
            <div class="col-lg-6 d-lg-none d-block">
                {% popular_posts %}
            </div>
        </div>
	</div>
</section>
<!-- =======================
Related blog END -->

</main>
<!-- **************** MAIN CONTENT END **************** -->

{% endblock content %}

blog/templates/blog/inclusion/last_posts.html
<h5>جدید ترین</h5>

{% for post in posts %}
<!-- Card START -->
<div class="row mb-2 mx-1">
    <div class="card shadow p-2">
                                <div class="row g-0">
                                    <div class="col-lg-5">
                                        <img src="{{ post.image.url }}" class="img-fluid rounded-2" alt="Card image">
                                    </div>
                                    <div class="col-lg-7">
                                        <div class="card-body">
                                            <!-- Badge and rating -->
                                            <div class="d-flex justify-content-between align-items-center mb-2">
                                                <!-- Badge -->
                                                <a href="#" class="badge text-bg-primary mb-2 mb-sm-0">Marketing</a>
                                                <!-- Rating and wishlist -->
                                                <div>
                                                    <span class="me-3"><i class="fas fa-star text-warning me-1"></i>4.5</span>
                                                    <a href="#" class="text-danger"><i class="far fa-heart"></i></a>
                                                </div>
                                            </div>

                                            <!-- Title -->
                                            <h5 class="card-title"><a href="#">{{ post.title }}</a></h5>
                                            <p class="text-truncate">{{ post.lead }}</p>

                                            <!-- Info -->
                                            <ul class="list-inline">
                                                <li class="list-inline-item  mb-1 mb-sm-0"><i class="far fa-clock text-danger me-2"></i>6h 56m</li>
                                                <li class="list-inline-item  mb-1 mb-sm-0"><i class="fas fa-table text-orange me-2"></i>82 lectures</li>
                                            </ul>


                                        </div>
                                    </div>
                                </div>
                                <!-- Price and avatar -->
                                <div class="d-sm-flex justify-content-sm-between align-items-center">
                                                <!-- Avatar -->
                                                <div class="d-flex align-items-center">
                                                    <div class="avatar">
                                                        <img class="avatar-img rounded-circle" src="{{ post.image.url }}" alt="avatar">
                                                    </div>
                                                    <p class="mb-0 ms-2"><a href="#" class="">Larry Lawson</a></p>
                                                </div>
                                                <!-- Price -->
                                                <div class="mt-3 mt-sm-0">
                                                    <a href="#" class="btn btn-blue">View more</a>
                                                </div>
                                            </div>
                            </div>
</div>
<!-- Card END -->
{% endfor %}

blog/templates/blog/inclusion/popular_posts.html
<h5>پست های محبوب</h5>

{% for post in posts %}
<!-- Card START -->
<div class="row mb-2 mx-1">
    <div class="card shadow p-2">
                                <div class="row g-0">
                                    <div class="col-lg-5">
                                        <img src="{{ post.image.url }}" class="img-fluid rounded-2" alt="Card image">
                                    </div>
                                    <div class="col-lg-7">
                                        <div class="card-body">
                                            <!-- Badge and rating -->
                                            <div class="d-flex justify-content-between align-items-center mb-2">
                                                <!-- Badge -->
                                                <a href="#" class="badge text-bg-primary mb-2 mb-sm-0">Marketing</a>
                                                <!-- Rating and wishlist -->
                                                <div>
                                                    <span class="me-3"><i class="fas fa-star text-warning me-1"></i>4.5</span>
                                                    <a href="#" class="text-danger"><i class="far fa-heart"></i></a>
                                                </div>
                                            </div>

                                            <!-- Title -->
                                            <h5 class="card-title"><a href="#">{{ post.title }}</a></h5>
                                            <p class="text-truncate">{{ post.lead }}</p>

                                            <!-- Info -->
                                            <ul class="list-inline">
                                                <li class="list-inline-item  mb-1 mb-sm-0"><i class="far fa-clock text-danger me-2"></i>6h 56m</li>
                                                <li class="list-inline-item  mb-1 mb-sm-0"><i class="fas fa-table text-orange me-2"></i>82 lectures</li>
                                            </ul>


                                        </div>
                                    </div>
                                </div>
                                <!-- Price and avatar -->
                                <div class="d-sm-flex justify-content-sm-between align-items-center">
                                                <!-- Avatar -->
                                                <div class="d-flex align-items-center">
                                                    <div class="avatar">
                                                        <img class="avatar-img rounded-circle" src="{{ post.image.url }}" alt="avatar">
                                                    </div>
                                                    <p class="mb-0 ms-2"><a href="#" class="">Larry Lawson</a></p>
                                                </div>
                                                <!-- Price -->
                                                <div class="mt-3 mt-sm-0">
                                                    <a href="#" class="btn btn-blue">View more</a>
                                                </div>
                                            </div>
                            </div>
</div>
<!-- Card END -->
{% endfor %}

index/templates/index/contact-us.html
{% extends "index/base.html" %}

{% load static %}

{% block content %}

<!-- **************** MAIN CONTENT START **************** -->
<main>
	
<!-- =======================
Page Banner START -->
<section class="pt-5 pb-0" style="background-image:url({% static 'images/element/map.svg' %}); background-position: center left; background-size: cover;">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-xl-6 text-center mx-auto">
				<!-- Title -->
				<h6 class="text-primary">ارتباط با ما</h6>
				<h1 class="mb-4">ما اینجاییم تا کمک کنیم!</h1>
			</div>
		</div>
		
		<!-- Contact info box -->
		<div class="row g-4 g-md-5 mt-0 mt-lg-3">
			<!-- Box item -->
			<div class="col-lg-4 mt-lg-0">
				<div class="card card-body bg-primary shadow py-5 text-center h-100">
					<!-- Title -->
					<h5 class="text-white mb-3">پشتیبانی مشتری</h5>
					<ul class="list-inline mb-0">
						<!-- Address -->
						<li class="list-item mb-3">
							<a href="#" class="text-white"> <i class="fas fa-fw fa-map-marker-alt me-2 mt-1"></i>یاسوج، خیابان معلم، معلم 2، سردار 4، ساختمان مثلث طلایی</a>
						</li>
						<!-- Phone number -->
						<li class="list-item mb-3">
							<a href="#" class="text-white"> <i class="fas fa-fw fa-phone-alt me-2"></i>0917-143-6506 </a>
						</li>
						<!-- Email id -->
						<li class="list-item mb-0">
							<a href="#" class="text-white"> <i class="far fa-fw fa-envelope me-2"></i>example@email.com </a>
						</li>
					</ul>
				</div>
			</div>

			<!-- Box item -->
			<div class="col-lg-4 mt-lg-0">
				<div class="card card-body shadow py-5 text-center h-100">
					<!-- Title -->
					<h5 class="mb-3">آدرس تماس</h5>
					<ul class="list-inline mb-0">
						<!-- Address -->
						<li class="list-item mb-3 h6 fw-light">
							<a href="#"> <i class="fas fa-fw fa-map-marker-alt me-2 mt-1"></i>یاسوج، خیابان معلم، معلم 2، سردار 4، ساختمان مثلث طلایی</a>
						</li>
						<!-- Phone number -->
						<li class="list-item mb-3 h6 fw-light">
							<a href="#"> <i class="fas fa-fw fa-phone-alt me-2"></i>0992-607-0541</a>
						</li>
						<!-- Email id -->
						<li class="list-item mb-0 h6 fw-light">
							<a href="#"> <i class="far fa-fw fa-envelope me-2"></i>example@email.com </a>
						</li>
					</ul>
				</div>
			</div>

			<!-- Box item -->
			<div class="col-lg-4 mt-lg-0">
				<div class="card card-body shadow py-5 text-center h-100">
					<!-- Title -->
					<h5 class="mb-3">آدرس دفتر اصلی</h5>
					<ul class="list-inline mb-0">
						<!-- Address -->
						<li class="list-item mb-3 h6 fw-light">
							<a href="#"> <i class="fas fa-fw fa-map-marker-alt me-2 mt-1"></i>یاسوج، خیابان معلم، معلم 2، سردار 4، ساختمان مثلث طلایی</a>
						</li>
						<!-- Phone number -->
						<li class="list-item mb-3 h6 fw-light">
							<a href="#"> <i class="fas fa-fw fa-phone-alt me-2"></i>0917-749-9862</a>
						</li>
						<!-- Email id -->
						<li class="list-item mb-0 h6 fw-light">
							<a href="#"> <i class="far fa-fw fa-envelope me-2"></i>example@email.com </a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- =======================
Page Banner END -->

<!-- =======================
Image and contact form START -->
<section >
	<div class="container">
		<div class="row g-4 g-lg-0 align-items-center">

			<div class="col-md-6 align-items-center text-center">
				<!-- Image -->
				<img src="{% static 'images/element/contact.svg' %}" class="h-400px" alt="">

				<!-- Social media button -->
				<div class="d-sm-flex align-items-center justify-content-center mt-2 mt-sm-4">
					<h5 class="mb-0">ارتباط با ما:</h5>
					<ul class="list-inline mb-0 ms-sm-2">
						<li class="list-inline-item"> <a class="fs-5 me-1 text-facebook" href="#"><i class="fab fa-fw fa-facebook-square"></i></a> </li>
						<li class="list-inline-item"> <a class="fs-5 me-1 text-instagram" href="#"><i class="fab fa-fw fa-instagram"></i></a> </li>
						<li class="list-inline-item"> <a class="fs-5 me-1 text-twitter" href="#"><i class="fab fa-fw fa-twitter"></i></a> </li>
						<li class="list-inline-item"> <a class="fs-5 me-1 text-linkedin" href="#"><i class="fab fa-fw fa-linkedin-in"></i></a> </li>
						<li class="list-inline-item"> <a class="fs-5 me-1 text-dribbble" href="#"><i class="fas fa-fw fa-basketball-ball"></i></a> </li>
						<li class="list-inline-item"> <a class="fs-5 me-1 text-pinterest" href="#"><i class="fab fa-fw fa-pinterest"></i></a> </li>
					</ul>
				</div>
			</div>

			<!-- Contact form START -->
			<div class="col-md-6">
				<!-- Title -->
				<h2 class="mt-4 mt-md-0">بیا حرف بزنیم</h2>
				<p>برای درخواست قیمت یا تمایل به ملاقات حضوری برای صرف قهوه، مستقیماً با ما تماس بگیرید یا فرم را پر کنید، ما به سرعت با شما تماس خواهیم گرفت.</p>
					
				<form>
					<!-- Name -->
					<div class="mb-4 bg-light-input">
						<label for="yourName" class="form-label">نام *</label>
						<input required type="text" class="form-control form-control-lg" id="yourName">
					</div>
					<!-- Email -->
					<div class="mb-4 bg-light-input">
						<label for="emailInput" class="form-label">ایمیل *</label>
						<input required type="email" class="form-control form-control-lg" id="emailInput">
					</div>
					<!-- Message -->
					<div class="mb-4 bg-light-input">
						<label for="textareaBox" class="form-label">پیام شما *</label>
						<textarea required class="form-control" id="textareaBox" rows="4"></textarea>
					</div>
					<!-- Button -->
					<div class="d-grid">
						<input class="btn btn-lg btn-primary mb-0" type="button" value="ارسال پییام">
					</div>	
				</form>
			</div>
			<!-- Contact form END -->
		</div>
	</div>
</section>
<!-- =======================
Image and contact form END -->

<!-- =======================
Map START -->
<section class="pt-0">
	<div class="container">
		<div class="row">
			<div class="col-12">
                <h3>اینجا باید با مپ به صورت آی فرام تکمیل شود</h3>
				<iframe class="w-100 h-400px grayscale rounded"  height="500" style="border:0;" aria-hidden="false" tabindex="0"></iframe>
			</div>
		</div>
	</div>
</section>
<!-- =======================
Map END -->

</main>
<!-- **************** MAIN CONTENT END **************** -->

{% endblock content %}